# Nom du projet DBT
name: 'dbt_postgres_project'
version: '1.0.0'

# Associer DBT à la bonne configuration de `profiles.yml`
profile: 'dbt_postgres_project'

# Définition des chemins où DBT doit chercher les fichiers
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Définition des répertoires à nettoyer avec `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_postgres_project:
    marts:
      +materialized: table  # Data marts seront des tables
    staging:
      +materialized: view   # Staging reste des vues